/**
 * Reusable JSON-LD schema generators for SEO/GEO.
 * Used by geo landing pages and blog articles to inject LocalBusiness,
 * BreadcrumbList and other schemas without duplicating boilerplate.
 */

export type CityKey =
  | "Bordeaux"
  | "Royan"
  | "Arcachon"
  | "Soulac"
  | "Pauillac"
  | "Lesparre"
  | "Montalivet"
  | "Lacanau";

interface CityInfo {
  postalCode: string;
  region: string;
  country: string; // ISO 3166-1 alpha-2
  lat: number;
  lon: number;
}

/** Postal codes and coordinates for each served city. */
export const CITIES: Record<CityKey, CityInfo> = {
  Bordeaux:   { postalCode: "33000", region: "Nouvelle-Aquitaine",   country: "FR", lat: 44.8378, lon: -0.5792 },
  Royan:      { postalCode: "17200", region: "Nouvelle-Aquitaine",   country: "FR", lat: 45.6259, lon: -1.0287 },
  Arcachon:   { postalCode: "33120", region: "Nouvelle-Aquitaine",   country: "FR", lat: 44.6580, lon: -1.1683 },
  Soulac:     { postalCode: "33780", region: "Nouvelle-Aquitaine",   country: "FR", lat: 45.5093, lon: -1.1281 },
  Pauillac:   { postalCode: "33250", region: "Nouvelle-Aquitaine",   country: "FR", lat: 45.1980, lon: -0.7475 },
  Lesparre:   { postalCode: "33340", region: "Nouvelle-Aquitaine",   country: "FR", lat: 45.3033, lon: -0.9347 },
  Montalivet: { postalCode: "33930", region: "Nouvelle-Aquitaine",   country: "FR", lat: 45.3987, lon: -1.1481 },
  Lacanau:    { postalCode: "33680", region: "Nouvelle-Aquitaine",   country: "FR", lat: 44.9783, lon: -1.1281 },
};

const SITE_URL = "https://www.nbn-ia.fr";
const ORG_ID = `${SITE_URL}/#organization`;
const OG_IMAGE = `${SITE_URL}/opengraph-image`; // dynamic OG generated by src/app/opengraph-image.tsx

/**
 * Generate a LocalBusiness schema for a specific city landing page.
 * Reuses the global @id for the parent organization to avoid duplication.
 */
export function localBusinessSchema(opts: {
  city: CityKey;
  pageUrl: string;          // canonical URL of the page
  name?: string;            // service-localized name, e.g. "NBN IA — Bordeaux"
  description: string;
  telephone?: string;
  priceRange?: string;      // "€€"
}) {
  const c = CITIES[opts.city];
  return {
    "@type": "LocalBusiness",
    "@id": `${opts.pageUrl}#localbusiness`,
    name: opts.name ?? `NBN IA — ${opts.city}`,
    url: opts.pageUrl,
    image: OG_IMAGE,
    description: opts.description,
    telephone: opts.telephone ?? "+33640685975",
    email: "contact@nbn-ia.fr",
    priceRange: opts.priceRange ?? "€€",
    address: {
      "@type": "PostalAddress",
      addressLocality: opts.city,
      addressRegion: c.region,
      postalCode: c.postalCode,
      addressCountry: c.country,
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: c.lat,
      longitude: c.lon,
    },
    areaServed: { "@type": "City", name: opts.city },
    parentOrganization: { "@id": ORG_ID },
    openingHoursSpecification: {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      opens: "09:00",
      closes: "18:00",
    },
    sameAs: ["https://www.linkedin.com/company/nbn-nocode"],
  };
}

/**
 * Generate a BreadcrumbList schema.
 * Pass items as { name, url } in order from root to current page.
 */
export function breadcrumbSchema(items: { name: string; url: string }[]) {
  return {
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  };
}

/** Convenience: build the standard 2-level breadcrumb (Accueil > Page). */
export function simpleBreadcrumb(pageName: string, pageUrl: string) {
  return breadcrumbSchema([
    { name: "Accueil", url: SITE_URL },
    { name: pageName, url: pageUrl },
  ]);
}
