import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";

export const metadata: Metadata = {
  title: "AI Automation for Hotels & Hospitality — France",
  description: "Automate check-in, guest communication, upselling and reviews for hotels in France. Claude AI agents running 24/7. Based in Bordeaux. Free audit.",
  keywords: ["hotel AI automation France", "hospitality AI Bordeaux", "hotel chatbot France", "automated check-in France", "guest experience AI", "hotel AI Arcachon Royan", "hospitality automation France"],
  alternates: { canonical: "https://www.nbn-ia.fr/en/hotel-ai-automation" },
};

export default function HotelAiPage() {
  return (
    <div className="min-h-screen bg-white pt-32 pb-24">
      <div className="max-w-4xl mx-auto px-6">
        <div className="inline-flex items-center gap-2 bg-orange-50 border border-orange-100 text-[#e8632a] rounded-full px-4 py-1.5 text-xs font-semibold mb-8 tracking-wide uppercase">
          🏨 AI for Hotels — France
        </div>
        <h1 className="text-4xl md:text-5xl font-bold text-gray-900 leading-tight mb-6">
          AI Automation for Hotels<br />
          <span className="text-[#e8632a]">& Hospitality in France</span>
        </h1>
        <p className="text-lg text-gray-500 max-w-2xl mb-10 leading-relaxed">
          From automated check-in to multilingual guest support — we build AI systems that handle guest operations 24/7, reduce staff workload and increase satisfaction scores.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 mb-20">
          <Link href="https://calendly.com/ben40nocode/1h" target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 bg-[#e8632a] hover:bg-[#c4521f] text-white px-7 py-4 rounded-xl font-semibold transition-colors">
            Book free audit <ArrowRight size={17} />
          </Link>
        </div>
        <div className="grid md:grid-cols-2 gap-12 mb-20">
          <div>
            <h2 className="text-2xl font-bold text-gray-900 mb-6">What we automate</h2>
            <ul className="space-y-4">
              {[
                "Automated check-in: confirmation, access codes, digital welcome guide",
                "Multilingual AI chatbot (EN/FR/DE/ES) for guest questions",
                "Upselling sequences: breakfast, spa, room upgrades",
                "Review request automation post-checkout",
                "Reservation follow-up & cancellation management",
                "Staff alert system for maintenance & requests",
              ].map((f) => (
                <li key={f} className="flex items-start gap-3">
                  <Check size={20} className="text-[#e8632a] flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">{f}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="bg-gray-50 rounded-2xl p-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4">Real result</h2>
            <p className="text-gray-500 text-sm leading-relaxed">
              A hotel on the Atlantic coast automated their full check-in workflow with AI: personalized welcome emails, digital access codes, local activity guide generated by Claude AI. <strong className="text-gray-700">Zero manual intervention per booking.</strong> Guest satisfaction scores increased 18% in 3 months.
            </p>
          </div>
        </div>
        <div className="bg-gray-900 rounded-3xl p-12 text-center">
          <h2 className="text-white font-bold text-2xl mb-3">Ready to automate your hotel?</h2>
          <p className="text-gray-300 mb-8 max-w-md mx-auto">Free audit. We map your guest journey and build the AI system. No commitment.</p>
          <Link href="https://calendly.com/ben40nocode/1h" target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 bg-[#e8632a] hover:bg-[#c4521f] text-white px-8 py-4 rounded-xl font-semibold transition-colors">
            Book free audit <ArrowRight size={16} />
          </Link>
        </div>
      </div>
    </div>
  );
}
