import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";

export const metadata: Metadata = {
  title: "AI Automation for Wine Estates & Châteaux | NBN IA Bordeaux",
  description: "AI systems for wine estates in Bordeaux and Médoc. Automate export sales, client follow-up, visit bookings and content generation. Claude AI agents. Free audit.",
  keywords: ["AI wine estate Bordeaux", "château automation", "AI winery France", "wine export automation", "Médoc AI agency", "Bordeaux wine AI", "château digital transformation", "wine tourism automation France"],
  alternates: { canonical: "https://www.nbn-ia.fr/en/wine-estate-ai" },
  openGraph: { title: "AI Automation for Wine Estates — Bordeaux | NBN IA", description: "Autonomous AI systems for châteaux and wine estates in Bordeaux and Médoc.", url: "https://www.nbn-ia.fr/en/wine-estate-ai" },
};

export default function WineEstateAiPage() {
  return (
    <div className="min-h-screen bg-white pt-32 pb-24">
      <div className="max-w-4xl mx-auto px-6">
        <div className="inline-flex items-center gap-2 bg-orange-50 border border-orange-100 text-[#e8632a] rounded-full px-4 py-1.5 text-xs font-semibold mb-8 tracking-wide uppercase">
          🍷 AI for Wine Estates — Bordeaux
        </div>
        <h1 className="text-4xl md:text-5xl font-bold text-gray-900 leading-tight mb-6">
          AI Automation for<br />
          <span className="text-[#e8632a]">Wine Estates & Châteaux</span>
        </h1>
        <p className="text-lg text-gray-500 max-w-2xl mb-10 leading-relaxed">
          From export client follow-up to wine tourism booking management — we build autonomous AI systems that handle your repetitive operations 24/7, so you can focus on your wines.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 mb-20">
          <Link href="https://calendly.com/ben40nocode/1h" target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 bg-[#e8632a] hover:bg-[#c4521f] text-white px-7 py-4 rounded-xl font-semibold transition-colors">
            Book free audit <ArrowRight size={17} />
          </Link>
        </div>
        <div className="grid md:grid-cols-2 gap-12 mb-20">
          <div>
            <h2 className="text-2xl font-bold text-gray-900 mb-6">What we automate for wine estates</h2>
            <ul className="space-y-4">
              {[
                "Export client follow-up & multilingual email sequences",
                "Wine tourism booking management & automated confirmations",
                "Social media content generation (tasting notes, harvest updates)",
                "B2B lead qualification for importers & distributors",
                "Inventory alerts & production tracking",
                "Multilingual chatbot for estate website visitors",
              ].map((f) => (
                <li key={f} className="flex items-start gap-3">
                  <Check size={20} className="text-[#e8632a] flex-shrink-0 mt-0.5" />
                  <span className="text-gray-700">{f}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="bg-gray-50 rounded-2xl p-8">
            <h2 className="text-xl font-bold text-gray-900 mb-4">Real example</h2>
            <p className="text-gray-500 text-sm leading-relaxed mb-4">
              A Médoc château automated their wine tourism welcome workflow: confirmation emails, personalized tasting guides generated by AI, access codes, post-visit follow-up. Result: <strong className="text-gray-700">0 manual intervention per booking</strong>.
            </p>
            <p className="text-gray-500 text-sm leading-relaxed">
              Export client AI agent handles initial contact in English, German and Chinese — qualifying leads before human intervention. <strong className="text-gray-700">3× more qualified conversations per week</strong>.
            </p>
          </div>
        </div>
        <div className="bg-gray-900 rounded-3xl p-12 text-center">
          <h2 className="text-white font-bold text-2xl mb-3">Interested for your estate?</h2>
          <p className="text-gray-300 mb-8 max-w-md mx-auto">Free 1-hour audit. We map your operations and propose a concrete AI architecture.</p>
          <Link href="https://calendly.com/ben40nocode/1h" target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-2 bg-[#e8632a] hover:bg-[#c4521f] text-white px-8 py-4 rounded-xl font-semibold transition-colors">
            Book free audit <ArrowRight size={16} />
          </Link>
        </div>
      </div>
    </div>
  );
}
